language: en

pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 3
- name: ftfeat.FastTextFeaturizer
  cache_dir: "/Users/vincent/Development/whatlies/"
  file: "cc.en.300.bin"
- name: printer.Printer
  alias: after fasttext
- name: printer.Printer
  alias: after outlier
- name: DIETClassifier
  epochs: 20

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
  - name: MappingPolicy
